### ISSUE TITLE
this.$$set is not a function

### ISSUE THREAD

**Issue by mattfysh** [hyperlab/svelte-error-boundary#7]
https://github.com/CrownFramework/svelte-error-boundary/blob/a92baeeea9ad8b4912c66fbcfa1dcc680ad67d69/src/createBoundary.js#L52

Is this a breakage on the internal Svelte API?

**Comment by gbrits** [comment]
I also just got this error, but this closed issue wasn't helpful in how to resolve it?
```
_slug_.62e7326c.js:1 Uncaught (in promise) TypeError: this.$$set is not a function
    at new <anonymous> (_slug_.62e7326c.js:1:2709)
    at fn (_slug_.62e7326c.js:1:35335)
    at p$ (client.be1ea105.js:1:130198)
    at new gn (_slug_.62e7326c.js:1:43265)
    at Array.OA (client.be1ea105.js:1:210903)
    at Array.IA (client.be1ea105.js:1:212755)
    at Mw (client.be1ea105.js:1:120737)
    at Array.hA (client.be1ea105.js:1:203688)
    at Mw (client.be1ea105.js:1:120737)
    at RS (client.be1ea105.js:1:194915)
```
